{"name": "test_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 2) == 5", "trace": "@pytest.mark.reg\n    def test_add():\n>       assert 2+2 == 5\nE       assert (2 + 2) == 5\n\n22_March_2024\\test_Lab001.py:12: AssertionError"}, "start": 1711367474884, "stop": 1711367474885, "uuid": "d575c5fe-77a4-407d-a729-7e00ce1a338c", "historyId": "9a2fd0dbf47391012eef3006ef923c9c", "testCaseId": "9a2fd0dbf47391012eef3006ef923c9c", "fullName": "22_March_2024.test_Lab001#test_add", "labels": [{"name": "tag", "value": "reg"}, {"name": "parentSuite", "value": "22_March_2024"}, {"name": "suite", "value": "test_Lab001"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "13892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "22_March_2024.test_Lab001"}]}